[package]
edition = "2021"
name = "query-poc"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
intmap = "2.0.0"
paste = "1.0"
